<a href="https://colab.research.google.com/github/chandradharvasireddy-19/25BDS0329/blob/main/exp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
dfI1= pd.DataFrame({'Jersey No': [9, 11, 13, 15, 17, 7, 21, 23, 25, 27, 29],'Score' : [22, 66, 31, 51, 71, 91, 56, 32, 52, 73, 92]})
dfI2=pd.DataFrame({'Jersey No': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30],'Score': [98, 93, 44, 77, 69, 56, 31, 53, 78, 93, 56, 77, 33, 56, 27]})
dfP1=pd.DataFrame({ 'Jersey No': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],'Score' : [39, 49, 55, 77, 52, 86, 41, 77, 73, 51, 86, 82, 92, 23, 49]})
dfP2=pd.DataFrame({'Jersey No': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],'Score': [93, 44, 78, 97, 87, 89, 39, 43, 88, 78]})

In [14]:
dfI=pd.concat([dfI1,dfI2],ignore_index=True)
dfP=pd.concat([dfP1,dfP2],ignore_index=True)
df=pd.concat([dfI,dfP],axis=1)
df

    Jersey No  Score  Jersey No  Score
0           9     22        1.0   39.0
1          11     66        3.0   49.0
2          13     31        5.0   55.0
3          15     51        7.0   77.0
4          17     71        9.0   52.0
5           7     91       11.0   86.0
6          21     56       13.0   41.0
7          23     32       15.0   77.0
8          25     52       17.0   73.0
9          27     73       19.0   51.0
10         29     92       21.0   86.0
11          2     98       23.0   82.0
12          4     93       25.0   92.0
13          6     44       27.0   23.0
14          8     77       29.0   49.0
15         10     69        2.0   93.0
16         12     56        4.0   44.0
17         14     31        6.0   78.0
18         16     53        8.0   97.0
19         18     78       10.0   87.0
20         20     93       12.0   89.0
21         22     56       14.0   39.0
22         24     77       16.0   43.0
23         26     33       18.0   88.0
24         28     56       20.0   78.0
25         30     27        NaN    NaN

In [17]:
df1=dfI.merge(dfP,how='inner')
df2=dfI.merge(dfP,how='left')
df3=dfI.merge(dfP,how='right')
df1
df2
df3

    Jersey No  Score
0           1     39
1           3     49
2           5     55
3           7     77
4           9     52
5          11     86
6          13     41
7          15     77
8          17     73
9          19     51
10         21     86
11         23     82
12         25     92
13         27     23
14         29     49
15          2     93
16          4     44
17          6     78
18          8     97
19         10     87
20         12     89
21         14     39
22         16     43
23         18     88
24         20     78