<a href="https://colab.research.google.com/github/chandradharvasireddy-19/25BDS0329/blob/main/exp4_28.07.2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
#missing values
import numpy as np
import pandas as pd
data = np.arange(10,25).reshape(5,3)
dfx=pd.DataFrame(data,index=['apple','samsung','redmi','nokia','Motorola'],columns=['shop1','shop2','shop3'])
dfx

          shop1  shop2  shop3
apple        10     11     12
samsung      13     14     15
redmi        16     17     18
nokia        19     20     21
Motorola     22     23     24

In [4]:
dfx['shop4']=np.nan
dfx.loc['oneplus']=np.arange(10,14)
dfx.loc['nothing']=np.nan
dfx['shop5']=np.nan
dfx['shop4']['apple']=23
dfx

/tmp/ipykernel_1372/4021829781.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfx['shop4']['apple']=23

          shop1  shop2  shop3  shop4  shop5
apple      10.0   11.0   12.0   23.0    NaN
samsung    13.0   14.0   15.0    NaN    NaN
redmi      16.0   17.0   18.0    NaN    NaN
nokia      19.0   20.0   21.0    NaN    NaN
Motorola   22.0   23.0   24.0    NaN    NaN
oneplus    10.0   11.0   12.0   13.0    NaN
nothing     NaN    NaN    NaN    NaN    NaN

In [5]:
#check whether null or not
dfx.isnull()

          shop1  shop2  shop3  shop4  shop5
apple     False  False  False  False   True
samsung   False  False  False   True   True
redmi     False  False  False   True   True
nokia     False  False  False   True   True
Motorola  False  False  False   True   True
oneplus   False  False  False  False   True
nothing    True   True   True   True   True

In [6]:
#checks not null
dfx.notnull()

          shop1  shop2  shop3  shop4  shop5
apple      True   True   True   True  False
samsung    True   True   True  False  False
redmi      True   True   True  False  False
nokia      True   True   True  False  False
Motorola   True   True   True  False  False
oneplus    True   True   True   True  False
nothing   False  False  False  False  False

In [7]:
#sum of null in each row
dfx.isnull().sum()

shop1    1
shop2    1
shop3    1
shop4    5
shop5    7
dtype: int64

In [8]:
#total sum of null in entire table
dfx.isnull().sum().sum()

np.int64(15)

In [9]:
#count no of reported values
dfx.count()

shop1    6
shop2    6
shop3    6
shop4    2
shop5    0
dtype: int64

In [10]:
#dropping missing values
dfx.shop4[dfx.shop4.notnull()]

apple      23.0
oneplus    13.0
Name: shop4, dtype: float64

In [11]:
dfx.shop4.dropna()

apple      23.0
oneplus    13.0
Name: shop4, dtype: float64

In [12]:
dfx.dropna(how='all')

          shop1  shop2  shop3  shop4  shop5
apple      10.0   11.0   12.0   23.0    NaN
samsung    13.0   14.0   15.0    NaN    NaN
redmi      16.0   17.0   18.0    NaN    NaN
nokia      19.0   20.0   21.0    NaN    NaN
Motorola   22.0   23.0   24.0    NaN    NaN
oneplus    10.0   11.0   12.0   13.0    NaN

In [13]:
dfx.dropna(how='all', axis=1)

          shop1  shop2  shop3  shop4
apple      10.0   11.0   12.0   23.0
samsung    13.0   14.0   15.0    NaN
redmi      16.0   17.0   18.0    NaN
nokia      19.0   20.0   21.0    NaN
Motorola   22.0   23.0   24.0    NaN
oneplus    10.0   11.0   12.0   13.0
nothing     NaN    NaN    NaN    NaN

In [16]:
ar1 = np.array([175, 250, np.nan, 300])
ser1 = pd.Series(ar1)
ser1

0    175.0
1    250.0
2      NaN
3    300.0
dtype: float64

In [19]:
ar1.mean(),ser1.mean()

(np.float64(nan), np.float64(241.66666666666666))

In [23]:
ser2=dfx.shop1
ser2.sum(),ser2.mean(),ser2.cumsum()

(np.int64(80),
 np.float64(16.0),
 apple       10
 samsung     23
 redmi       39
 nokia       58
 Motorola    80
 Name: shop1, dtype: int64)

In [24]:
filledDf=dfx.fillna(0)
filledDf

          shop1  shop2  shop3
apple        10     11     12
samsung      13     14     15
redmi        16     17     18
nokia        19     20     21
Motorola     22     23     24

In [26]:
dfx.mean(),filledDf.mean()

(shop1    16.0
 shop2    17.0
 shop3    18.0
 dtype: float64,
 shop1    16.0
 shop2    17.0
 shop3    18.0
 dtype: float64)

In [28]:
dfx.shop2.fillna(method='ffill')

/tmp/ipykernel_1372/1120153916.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.shop2.fillna(method='ffill')

apple       11
samsung     14
redmi       17
nokia       20
Motorola    23
Name: shop2, dtype: int64

In [29]:
dfx.shop2.fillna(method='bfill')

/tmp/ipykernel_1372/489511885.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.shop2.fillna(method='bfill')

apple       11
samsung     14
redmi       17
nokia       20
Motorola    23
Name: shop2, dtype: int64

In [37]:
#imputations Techique
import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer
#creating data
df = pd.DataFrame( { "Age": [26, np.nan, 29, 50, 24], "Salary": [50000, 60000, 90000, np.nan, 45000], "Category": ["A", np.nan, "A", "C", "B"], })
df

    Age   Salary Category
0  26.0  50000.0        A
1   NaN  60000.0      NaN
2  29.0  90000.0        A
3  50.0      NaN        C
4  24.0  45000.0        B

In [36]:
#mean Imputation
mi=SimpleImputer(strategy="mean")
df["Age_Mean"] = mi.fit_transform(df[["Age"]])
df

    Age   Salary Category  Age_Mean
0  26.0  50000.0        A     26.00
1   NaN  60000.0      NaN     32.25
2  29.0  90000.0        A     29.00
3  50.0      NaN        C     50.00
4  24.0  45000.0        B     24.00

In [40]:
mei=SimpleImputer(strategy="median")
df["Salary_Median"] = mei.fit_transform(df[["Salary"]])
df

    Age   Salary Category  Salary_Median
0  26.0  50000.0        A        50000.0
1   NaN  60000.0      NaN        60000.0
2  29.0  90000.0        A        90000.0
3  50.0      NaN        C        55000.0
4  24.0  45000.0        B        45000.0

In [47]:
moi = SimpleImputer(strategy="most_frequent")
df[["Category_Mode"]] = moi.fit_transform(df[["Category"]])
df

    Age   Salary Category  Salary_Median Category_Mode
0  26.0  50000.0        A        50000.0             A
1   NaN  60000.0      NaN        60000.0             A
2  29.0  90000.0        A        90000.0             A
3  50.0      NaN        C        55000.0             C
4  24.0  45000.0        B        45000.0             B

In [49]:
# (Multivariate Imputation by Chained Equations)
num_cols = ["Age", "Salary"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = df[num_cols].copy()
df_mice.iloc[:, :] = mice_imputer.fit_transform(df_mice)
df["Age_MICE"] = df_mice["Age"]
df["Salary_MICE"] = df_mice["Salary"]
df

    Age   Salary Category  Salary_Median Category_Mode   Age_MICE  Salary_MICE
0  26.0  50000.0        A        50000.0             A  26.000000  50000.00000
1   NaN  60000.0      NaN        60000.0             A  32.114786  60000.00000
2  29.0  90000.0        A        90000.0             A  29.000000  90000.00000
3  50.0      NaN        C        55000.0             C  50.000000  61250.00814
4  24.0  45000.0        B        45000.0             B  24.000000  45000.00000